---
title: "Instructions"
author: "Ralph Møller Trane"
format: 
  html:
    self-contained: true
---

## Downloads

The following .zip files should be downloaded from the [HRS Data Downloads site](https://hrsdata.isr.umich.edu/data-products/) and placed in the `data/HRS-zips` folder. We include links to data pages with details for each set of files, and also direct links for download. A log in is needed to download the data.

* HRS Survey Data:
  - [1998 HRS Core](https://hrsdata.isr.umich.edu/data-products/1998-hrs-core): [h98da.zip](https://hrsdata.isr.umich.edu/data-file-download/5515) and [h98sas.zip](https://hrsdata.isr.umich.edu/data-file-download/5625)
  - [2000 HRS Core](https://hrsdata.isr.umich.edu/data-products/2000-hrs-core): [h00da.zip](https://hrsdata.isr.umich.edu/data-file-download/5508) and [h00sas.zip](https://hrsdata.isr.umich.edu/data-file-download/5640)
  - [2002 HRS Core](https://hrsdata.isr.umich.edu/data-products/2002-hrs-core): [h02da.zip](https://hrsdata.isr.umich.edu/data-file-download/5506) and [h02sas.zip](https://hrsdata.isr.umich.edu/data-file-download/5637)
  - [2004 HRS Core](https://hrsdata.isr.umich.edu/data-products/2004-hrs-core): [h04da.zip](https://hrsdata.isr.umich.edu/data-file-download/5516) and [h04sas.zip](https://hrsdata.isr.umich.edu/data-file-download/5645)
  - [2006 HRS Core](https://hrsdata.isr.umich.edu/data-products/2006-hrs-core): [h06da.zip](https://hrsdata.isr.umich.edu/data-file-download/9480) and [h06sas.zip](https://hrsdata.isr.umich.edu/data-file-download/9483)
  - [2008 HRS Core](https://hrsdata.isr.umich.edu/data-products/2008-hrs-core): [h08da.zip](https://hrsdata.isr.umich.edu/data-file-download/5510) and [h08sas.zip](https://hrsdata.isr.umich.edu/data-file-download/5652)
  - [2010 HRS Core](https://hrsdata.isr.umich.edu/data-products/2010-hrs-core): [h10da.zip](https://hrsdata.isr.umich.edu/data-file-download/9464) and [h10sas.zip](https://hrsdata.isr.umich.edu/data-file-download/9466)

* RAND HRS Data:
  - We need an older version of the RAND data, the so-called Version P. This can be found under [archived data versions](https://hrsdata.isr.umich.edu/data-products/rand-hrs-archived-data-products).<br>
    The file needed: 
        - RAND HRS Version P [`randhrsp_archive_SAS.zip`](https://hrsdata.isr.umich.edu/data-file-download/5414)

* ADAMS Data:
  - From the main HRS Data Downloads page, navigate to [HRS Sensitive Health Data](https://hrsdata.isr.umich.edu/data-products/sensitive-health). Note: additional permissions are needed to access this part of the data.<br>
    The files to be downloaded are:
      - [Wave A](https://hrsdata.isr.umich.edu/data-products/aging-demographics-and-memory-study-adams-wave): [adams1a.zip](https://hrsdata.isr.umich.edu/data-file-download/5539)
      - [Wave B](https://hrsdata.isr.umich.edu/data-products/aging-demographics-and-memory-study-adams-wave-b): [adams1b.zip](https://hrsdata.isr.umich.edu/data-file-download/5616)
      - [CrossWave](https://hrsdata.isr.umich.edu/data-products/aging-demographics-and-memory-study-adams-cross-wave-tracker-file): [adams1trk.zip](https://hrsdata.isr.umich.edu/data-file-download/5570) 
