name: copy-readme
run-name: ${{ github.actor }} is copying README.md to root
on: [push]
jobs:
  cp-README:
    runs-on: ubuntu-latest
    steps:
      - run: cp ${{ github.workspace }}/qmd-documents/README.md ${{ github.workspace }}/README.md